[package]
name = "http_server"
version = "1.0.0"
edition = "2021"
authors = ["Lesoorub"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
